name: PHP Swoole CI

on:
  push:
    tags: 'php_swoole-**'

env:
  7.1: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
  7.2: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
  7.3: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
  7.4: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8

jobs:
  build-php:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php_version: ['7.1', '7.2', '7.3', '7.4']
        type: ['cli']
        swoole_version: ['4.7.0']
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images:
            baoziyoo/base-images
          flavor: |
            suffix=-php-${{ matrix.type }}-swoole-${{ matrix.php_version }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u baoziyoo --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./php-swoole/Dockerfile
          platforms: ${{ env[matrix.php_version] }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_TYPE=${{ matrix.type }}
            SWOOLE_VERSION=${{matrix.swoole_version}}
          
      - name: Logout
        run: docker logout
