name: PHP Swoole CI

on:
  workflow_run:
    workflows: [ PHP Base Image CI ]
    types:
      - completed

env:
  7.1: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
  7.2: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
  7.3: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
  7.4: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8

jobs:
  build-php:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php_version: [ '7.1', '7.2', '7.3', '7.4' ]
        type: [ 'cli' ]
    steps:
      - uses: actions/checkout@v2

      - name: Get Swoole Version
        id: vars
        run: |
          response=curl -s https://github.com/swoole/swoole-src/releases
          swoole_version=$($response | grep '/swoole/swoole-src/releases/tag/v' | head -n 1 | sed 's/.*\"\>v\([0-9]*.[0-9]*.[0-9]*\).*/\1/g')
          echo "::set-output name=swoole_version::$swoole_version"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images:
            baoziyoo/base-images
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u baoziyoo --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./php-swoole/Dockerfile
          platforms: ${{ env[matrix.php_version] }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_TYPE=${{ matrix.type }}
            SWOOLE_VERSION=${{steps.vars.outputs.swoole_version}}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: baoziyoo
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: baoziyoo/base-images
          short-description: ${{ github.event.repository.description }}

      - name: Logout
        run: docker logout
