name: PHP Base Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
env:
  platforms: linux/amd64,linux/arm/v6,linux/arm/v7

jobs:
  build-php:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php_version: ['5.6', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        type: [ 'cli', 'fpm' ]
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images:
            baoziyoo/base-images
          flavor: |
            latest=false
            prefix=php-${{ matrix.type }}-${{ matrix.php_version }}
          tags: |
            type=raw,value=

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u baoziyoo --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./php/Dockerfile
          platforms: ${{ env.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_TYPE=${{ matrix.type }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: baoziyoo
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: baoziyoo/base-images
          short-description: ${{ github.event.repository.description }}

      - name: Logout
        run: docker logout
